FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && pip install fastapi uvicorn jinja2 python-multipart starlette itsdangerous
COPY ./src ./src
CMD ["uvicorn", "src.web_admin.main:app", "--host", "0.0.0.0", "--port", "8000"] 