version: '3.9'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  webadmin:
    build:
      context: .
      dockerfile: Dockerfile.webadmin
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/web_admin:/app/src/web_admin
    command: ["uvicorn", "src.web_admin.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
  redisdata: 